<?php

namespace Pfrug\Period;

/**
 * @package Pfrug\Period
 */
class TimeZone
{
    public const TZ_UTC = 'UTC';

    public const TZ_AF = 'Asia/Kabul';
    public const TZ_AX = 'Europe/Mariehamn';
    public const TZ_AL = 'Europe/Tirane';
    public const TZ_DZ = 'Africa/Algiers';
    public const TZ_AS = 'Pacific/Pago_Pago';
    public const TZ_AD = 'Europe/Andorra';
    public const TZ_AO = 'Africa/Luanda';
    public const TZ_AI = 'America/Anguilla';
    public const TZ_AQ_CA = 'Antarctica/Casey';
    public const TZ_AQ_DA = 'Antarctica/Davis';
    public const TZ_AQ_DU = 'Antarctica/DumontDUrville';
    public const TZ_AQ_MA = 'Antarctica/Mawson';
    public const TZ_AQ_MC = 'Antarctica/McMurdo';
    public const TZ_AQ_PA = 'Antarctica/Palmer';
    public const TZ_AQ_RO = 'Antarctica/Rothera';
    public const TZ_AQ_SY = 'Antarctica/Syowa';
    public const TZ_AQ_TR = 'Antarctica/Troll';
    public const TZ_AQ_VO = 'Antarctica/Vostok';
    public const TZ_AG = 'America/Antigua';
    public const TZ_AR_BU = 'America/Argentina/Buenos_Aires';
    public const TZ_AR_CA = 'America/Argentina/Catamarca';
    public const TZ_AR_CO = 'America/Argentina/Cordoba';
    public const TZ_AR_JU = 'America/Argentina/Jujuy';
    public const TZ_AR_LA = 'America/Argentina/La_Rioja';
    public const TZ_AR_ME = 'America/Argentina/Mendoza';
    public const TZ_AR_RI = 'America/Argentina/Rio_Gallegos';
    public const TZ_AR_SA = 'America/Argentina/Salta';
    public const TZ_AR_SAJ = 'America/Argentina/San_Juan';
    public const TZ_AR_SAL = 'America/Argentina/San_Luis';
    public const TZ_AR_TU = 'America/Argentina/Tucuman';
    public const TZ_AR_US = 'America/Argentina/Ushuaia';
    public const TZ_AM = 'Asia/Yerevan';
    public const TZ_AW = 'America/Aruba';
    public const TZ_AU_MA = 'Antarctica/Macquarie';
    public const TZ_AU_AD = 'Australia/Adelaide';
    public const TZ_AU_BRI = 'Australia/Brisbane';
    public const TZ_AU_BRO = 'Australia/Broken_Hill';
    public const TZ_AU_DA = 'Australia/Darwin';
    public const TZ_AU_EU = 'Australia/Eucla';
    public const TZ_AU_HO = 'Australia/Hobart';
    public const TZ_AU_LI = 'Australia/Lindeman';
    public const TZ_AU_LO = 'Australia/Lord_Howe';
    public const TZ_AU_ME = 'Australia/Melbourne';
    public const TZ_AU_PE = 'Australia/Perth';
    public const TZ_AU_SY = 'Australia/Sydney';
    public const TZ_AT = 'Europe/Vienna';
    public const TZ_AZ = 'Asia/Baku';
    public const TZ_BS = 'America/Nassau';
    public const TZ_BH = 'Asia/Bahrain';
    public const TZ_BD = 'Asia/Dhaka';
    public const TZ_BB = 'America/Barbados';
    public const TZ_BY = 'Europe/Minsk';
    public const TZ_BE = 'Europe/Brussels';
    public const TZ_BZ = 'America/Belize';
    public const TZ_BJ = 'Africa/Porto-Novo';
    public const TZ_BM = 'Atlantic/Bermuda';
    public const TZ_BT = 'Asia/Thimphu';
    public const TZ_BO = 'America/La_Paz';
    public const TZ_BA = 'Europe/Sarajevo';
    public const TZ_BW = 'Africa/Gaborone';
    public const TZ_BR_AR = 'America/Araguaina';
    public const TZ_BR_BA = 'America/Bahia';
    public const TZ_BR_BE = 'America/Belem';
    public const TZ_BR_BO = 'America/Boa_Vista';
    public const TZ_BR_CA = 'America/Campo_Grande';
    public const TZ_BR_CU = 'America/Cuiaba';
    public const TZ_BR_EI = 'America/Eirunepe';
    public const TZ_BR_FO = 'America/Fortaleza';
    public const TZ_BR_MAC = 'America/Maceio';
    public const TZ_BR_MAN = 'America/Manaus';
    public const TZ_BR_NO = 'America/Noronha';
    public const TZ_BR_PO = 'America/Porto_Velho';
    public const TZ_BR_RE = 'America/Recife';
    public const TZ_BR_RI = 'America/Rio_Branco';
    public const TZ_BR_SA = 'America/Santarem';
    public const TZ_BR_SP = 'America/Sao_Paulo';
    public const TZ_IO = 'Indian/Chagos';
    public const TZ_BN = 'Asia/Brunei';
    public const TZ_BG = 'Europe/Sofia';
    public const TZ_BF = 'Africa/Ouagadougou';
    public const TZ_BI = 'Africa/Bujumbura';
    public const TZ_KH = 'Asia/Phnom_Penh';
    public const TZ_CM = 'Africa/Douala';
    public const TZ_CA_AT = 'America/Atikokan';
    public const TZ_CA_BL = 'America/Blanc-Sablon';
    public const TZ_CA_CA = 'America/Cambridge_Bay';
    public const TZ_CA_CR = 'America/Creston';
    public const TZ_CA_DA = 'America/Dawson';
    public const TZ_CA_DC = 'America/Dawson_Creek';
    public const TZ_CA_ED = 'America/Edmonton';
    public const TZ_CA_FO = 'America/Fort_Nelson';
    public const TZ_CA_GL = 'America/Glace_Bay';
    public const TZ_CA_GO = 'America/Goose_Bay';
    public const TZ_CA_HA = 'America/Halifax';
    public const TZ_CA_IN = 'America/Inuvik';
    public const TZ_CA_IQ = 'America/Iqaluit';
    public const TZ_CA_MO = 'America/Moncton';
    public const TZ_CA_NI = 'America/Nipigon';
    public const TZ_CA_PA = 'America/Pangnirtung';
    public const TZ_CA_RR = 'America/Rainy_River';
    public const TZ_CA_RI = 'America/Rankin_Inlet';
    public const TZ_CA_REG = 'America/Regina';
    public const TZ_CA_RES = 'America/Resolute';
    public const TZ_CA_ST = 'America/St_Johns';
    public const TZ_CA_SW = 'America/Swift_Current';
    public const TZ_CA_TH = 'America/Thunder_Bay';
    public const TZ_CA_TO = 'America/Toronto';
    public const TZ_CA_VA = 'America/Vancouver';
    public const TZ_CA_WH = 'America/Whitehorse';
    public const TZ_CA_WI = 'America/Winnipeg';
    public const TZ_CA_YE = 'America/Yellowknife';
    public const TZ_CV = 'Atlantic/Cape_Verde';
    public const TZ_KY = 'America/Cayman';
    public const TZ_CF = 'Africa/Bangui';
    public const TZ_TD = 'Africa/Ndjamena';
    public const TZ_CL_PU = 'America/Punta_Arenas';
    public const TZ_CL_SA = 'America/Santiago';
    public const TZ_CL_EA = 'Pacific/Easter';
    public const TZ_CN_SH = 'Asia/Shanghai';
    public const TZ_CN_UR = 'Asia/Urumqi';
    public const TZ_CX = 'Indian/Christmas';
    public const TZ_CC = 'Indian/Cocos';
    public const TZ_CO = 'America/Bogota';
    public const TZ_KM = 'Indian/Comoro';
    public const TZ_CG = 'Africa/Brazzaville';
    public const TZ_CD_KI = 'Africa/Kinshasa';
    public const TZ_CD_LU = 'Africa/Lubumbashi';
    public const TZ_CK = 'Pacific/Rarotonga';
    public const TZ_CR = 'America/Costa_Rica';
    public const TZ_CI = 'Africa/Abidjan';
    public const TZ_HR = 'Europe/Zagreb';
    public const TZ_CU = 'America/Havana';
    public const TZ_CY_FA = 'Asia/Famagusta';
    public const TZ_CY_NI = 'Asia/Nicosia';
    public const TZ_CZ = 'Europe/Prague';
    public const TZ_DK = 'Europe/Copenhagen';
    public const TZ_DJ = 'Africa/Djibouti';
    public const TZ_DM = 'America/Dominica';
    public const TZ_DO = 'America/Santo_Domingo';
    public const TZ_EC_GU = 'America/Guayaquil';
    public const TZ_EC_GA = 'Pacific/Galapagos';
    public const TZ_EG = 'Africa/Cairo';
    public const TZ_SV = 'America/El_Salvador';
    public const TZ_GQ = 'Africa/Malabo';
    public const TZ_ER = 'Africa/Asmara';
    public const TZ_EE = 'Europe/Tallinn';
    public const TZ_ET = 'Africa/Addis_Ababa';
    public const TZ_FK = 'Atlantic/Stanley';
    public const TZ_FO = 'Atlantic/Faroe';
    public const TZ_FJ = 'Pacific/Fiji';
    public const TZ_FI = 'Europe/Helsinki';
    public const TZ_FR = 'Europe/Paris';
    public const TZ_GF = 'America/Cayenne';
    public const TZ_PF_GA = 'Pacific/Gambier';
    public const TZ_PF_MA = 'Pacific/Marquesas';
    public const TZ_PF_TA = 'Pacific/Tahiti';
    public const TZ_TF = 'Indian/Kerguelen';
    public const TZ_GA = 'Africa/Libreville';
    public const TZ_GM = 'Africa/Banjul';
    public const TZ_GE = 'Asia/Tbilisi';
    public const TZ_DE_BE = 'Europe/Berlin';
    public const TZ_DE_BU = 'Europe/Busingen';
    public const TZ_GH = 'Africa/Accra';
    public const TZ_GI = 'Europe/Gibraltar';
    public const TZ_GR = 'Europe/Athens';
    public const TZ_GL_DA = 'America/Danmarkshavn';
    public const TZ_GL_NU = 'America/Nuuk';
    public const TZ_GL_SC = 'America/Scoresbysund';
    public const TZ_GL_TH = 'America/Thule';
    public const TZ_GD = 'America/Grenada';
    public const TZ_GP = 'America/Guadeloupe';
    public const TZ_GU = 'Pacific/Guam';
    public const TZ_GT = 'America/Guatemala';
    public const TZ_GG = 'Europe/Guernsey';
    public const TZ_GN = 'Africa/Conakry';
    public const TZ_GW = 'Africa/Bissau';
    public const TZ_GY = 'America/Guyana';
    public const TZ_HT = 'America/Port-au-Prince';
    public const TZ_VA = 'Europe/Vatican';
    public const TZ_HN = 'America/Tegucigalpa';
    public const TZ_HK = 'Asia/Hong_Kong';
    public const TZ_HU = 'Europe/Budapest';
    public const TZ_IS = 'Atlantic/Reykjavik';
    public const TZ_IN = 'Asia/Kolkata';
    public const TZ_ID_JAK = 'Asia/Jakarta';
    public const TZ_ID_JAY = 'Asia/Jayapura';
    public const TZ_ID_MA = 'Asia/Makassar';
    public const TZ_ID_PO = 'Asia/Pontianak';
    public const TZ_IR = 'Asia/Tehran';
    public const TZ_IQ = 'Asia/Baghdad';
    public const TZ_IE = 'Europe/Dublin';
    public const TZ_IM = 'Europe/Isle_of_Man';
    public const TZ_IL = 'Asia/Jerusalem';
    public const TZ_IT = 'Europe/Rome';
    public const TZ_JM = 'America/Jamaica';
    public const TZ_JP = 'Asia/Tokyo';
    public const TZ_JE = 'Europe/Jersey';
    public const TZ_JO = 'Asia/Amman';
    public const TZ_KZ_AL = 'Asia/Almaty';
    public const TZ_KZ_AQTAU = 'Asia/Aqtau';
    public const TZ_KZ_AQTOBE = 'Asia/Aqtobe';
    public const TZ_KZ_AT = 'Asia/Atyrau';
    public const TZ_KZ_OR = 'Asia/Oral';
    public const TZ_KZ_QO = 'Asia/Qostanay';
    public const TZ_KZ_QY = 'Asia/Qyzylorda';
    public const TZ_KE = 'Africa/Nairobi';
    public const TZ_KI_EN = 'Pacific/Enderbury';
    public const TZ_KI_KI = 'Pacific/Kiritimati';
    public const TZ_KI_TA = 'Pacific/Tarawa';
    public const TZ_KR = 'Asia/Seoul';
    public const TZ_KW = 'Asia/Kuwait';
    public const TZ_KG = 'Asia/Bishkek';
    public const TZ_LA = 'Asia/Vientiane';
    public const TZ_LV = 'Europe/Riga';
    public const TZ_LB = 'Asia/Beirut';
    public const TZ_LS = 'Africa/Maseru';
    public const TZ_LR = 'Africa/Monrovia';
    public const TZ_LY = 'Africa/Tripoli';
    public const TZ_LI = 'Europe/Vaduz';
    public const TZ_LT = 'Europe/Vilnius';
    public const TZ_LU = 'Europe/Luxembourg';
    public const TZ_MO = 'Asia/Macau';
    public const TZ_MK = 'Europe/Skopje';
    public const TZ_MG = 'Indian/Antananarivo';
    public const TZ_MW = 'Africa/Blantyre';
    public const TZ_MY_KL = 'Asia/Kuala_Lumpur';
    public const TZ_MY_KU = 'Asia/Kuching';
    public const TZ_MV = 'Indian/Maldives';
    public const TZ_ML = 'Africa/Bamako';
    public const TZ_MT = 'Europe/Malta';
    public const TZ_MH_KW = 'Pacific/Kwajalein';
    public const TZ_MH_MA = 'Pacific/Majuro';
    public const TZ_MQ = 'America/Martinique';
    public const TZ_MR = 'Africa/Nouakchott';
    public const TZ_MU = 'Indian/Mauritius';
    public const TZ_YT = 'Indian/Mayotte';
    public const TZ_MX_BA = 'America/Bahia_Banderas';
    public const TZ_MX_CA = 'America/Cancun';
    public const TZ_MX_CH = 'America/Chihuahua';
    public const TZ_MX_HE = 'America/Hermosillo';
    public const TZ_MX_MAT = 'America/Matamoros';
    public const TZ_MX_MAZ = 'America/Mazatlan';
    public const TZ_MX_ME = 'America/Merida';
    public const TZ_MX_DF = 'America/Mexico_City';
    public const TZ_MX_MO = 'America/Monterrey';
    public const TZ_MX_OJ = 'America/Ojinaga';
    public const TZ_MX_TI = 'America/Tijuana';
    public const TZ_FM_CH = 'Pacific/Chuuk';
    public const TZ_FM_KO = 'Pacific/Kosrae';
    public const TZ_FM_PO = 'Pacific/Pohnpei';
    public const TZ_MD = 'Europe/Chisinau';
    public const TZ_MC = 'Europe/Monaco';
    public const TZ_MN_CH = 'Asia/Choibalsan';
    public const TZ_MN_HO = 'Asia/Hovd';
    public const TZ_MN_UL = 'Asia/Ulaanbaatar';
    public const TZ_ME = 'Europe/Podgorica';
    public const TZ_MS = 'America/Montserrat';
    public const TZ_MA = 'Africa/Casablanca';
    public const TZ_MZ = 'Africa/Maputo';
    public const TZ_MM = 'Asia/Yangon';
    public const TZ_NA = 'Africa/Windhoek';
    public const TZ_NR = 'Pacific/Nauru';
    public const TZ_NP = 'Asia/Kathmandu';
    public const TZ_NL = 'Europe/Amsterdam';
    public const TZ_NC = 'Pacific/Noumea';
    public const TZ_NZ_AU = 'Pacific/Auckland';
    public const TZ_NZ_CH = 'Pacific/Chatham';
    public const TZ_NI = 'America/Managua';
    public const TZ_NE = 'Africa/Niamey';
    public const TZ_NG = 'Africa/Lagos';
    public const TZ_NU = 'Pacific/Niue';
    public const TZ_NF = 'Pacific/Norfolk';
    public const TZ_MP = 'Pacific/Saipan';
    public const TZ_NO = 'Europe/Oslo';
    public const TZ_OM = 'Asia/Muscat';
    public const TZ_PK = 'Asia/Karachi';
    public const TZ_PW = 'Pacific/Palau';
    public const TZ_PS_GA = 'Asia/Gaza';
    public const TZ_PS_HE = 'Asia/Hebron';
    public const TZ_PA = 'America/Panama';
    public const TZ_PG_BO = 'Pacific/Bougainville';
    public const TZ_PG_PO = 'Pacific/Port_Moresby';
    public const TZ_PY = 'America/Asuncion';
    public const TZ_PE = 'America/Lima';
    public const TZ_PH = 'Asia/Manila';
    public const TZ_PN = 'Pacific/Pitcairn';
    public const TZ_PL = 'Europe/Warsaw';
    public const TZ_PT_AZ = 'Atlantic/Azores';
    public const TZ_PT_MA = 'Atlantic/Madeira';
    public const TZ_PT_LI = 'Europe/Lisbon';
    public const TZ_PR = 'America/Puerto_Rico';
    public const TZ_QA = 'Asia/Qatar';
    public const TZ_RE = 'Indian/Reunion';
    public const TZ_RO = 'Europe/Bucharest';
    public const TZ_RU_AN = 'Asia/Anadyr';
    public const TZ_RU_BA = 'Asia/Barnaul';
    public const TZ_RU_CH = 'Asia/Chita';
    public const TZ_RU_IR = 'Asia/Irkutsk';
    public const TZ_RU_KA = 'Asia/Kamchatka';
    public const TZ_RU_KH = 'Asia/Khandyga';
    public const TZ_RU_KR = 'Asia/Krasnoyarsk';
    public const TZ_RU_MA = 'Asia/Magadan';
    public const TZ_RU_NOK = 'Asia/Novokuznetsk';
    public const TZ_RU_NOS = 'Asia/Novosibirsk';
    public const TZ_RU_OM = 'Asia/Omsk';
    public const TZ_RU_SA = 'Asia/Sakhalin';
    public const TZ_RU_SR = 'Asia/Srednekolymsk';
    public const TZ_RU_TO = 'Asia/Tomsk';
    public const TZ_RU_US = 'Asia/Ust-Nera';
    public const TZ_RU_VL = 'Asia/Vladivostok';
    public const TZ_RU_YA = 'Asia/Yakutsk';
    public const TZ_RU_YE = 'Asia/Yekaterinburg';
    public const TZ_RU_AS = 'Europe/Astrakhan';
    public const TZ_RU_KAL = 'Europe/Kaliningrad';
    public const TZ_RU_KI = 'Europe/Kirov';
    public const TZ_RU_MO = 'Europe/Moscow';
    public const TZ_RU_SAMARA = 'Europe/Samara';
    public const TZ_RU_SARATOC = 'Europe/Saratov';
    public const TZ_RU_UL = 'Europe/Ulyanovsk';
    public const TZ_RU_VO = 'Europe/Volgograd';
    public const TZ_RW = 'Africa/Kigali';
    public const TZ_BL = 'America/St_Barthelemy';
    public const TZ_SH = 'Atlantic/St_Helena';
    public const TZ_KN = 'America/St_Kitts';
    public const TZ_LC = 'America/St_Lucia';
    public const TZ_MF = 'America/Marigot';
    public const TZ_PM = 'America/Miquelon';
    public const TZ_VC = 'America/St_Vincent';
    public const TZ_WS = 'Pacific/Apia';
    public const TZ_SM = 'Europe/San_Marino';
    public const TZ_ST = 'Africa/Sao_Tome';
    public const TZ_SA = 'Asia/Riyadh';
    public const TZ_SN = 'Africa/Dakar';
    public const TZ_RS = 'Europe/Belgrade';
    public const TZ_SC = 'Indian/Mahe';
    public const TZ_SL = 'Africa/Freetown';
    public const TZ_SG = 'Asia/Singapore';
    public const TZ_SK = 'Europe/Bratislava';
    public const TZ_SI = 'Europe/Ljubljana';
    public const TZ_SB = 'Pacific/Guadalcanal';
    public const TZ_SO = 'Africa/Mogadishu';
    public const TZ_ZA = 'Africa/Johannesburg';
    public const TZ_GS = 'Atlantic/South_Georgia';
    public const TZ_ES_CE = 'Africa/Ceuta';
    public const TZ_ES_CA = 'Atlantic/Canary';
    public const TZ_ES_MA = 'Europe/Madrid';
    public const TZ_LK = 'Asia/Colombo';
    public const TZ_SD = 'Africa/Khartoum';
    public const TZ_SR = 'America/Paramaribo';
    public const TZ_SJ = 'Arctic/Longyearbyen';
    public const TZ_SZ = 'Africa/Mbabane';
    public const TZ_SE = 'Europe/Stockholm';
    public const TZ_CH = 'Europe/Zurich';
    public const TZ_SY = 'Asia/Damascus';
    public const TZ_TW = 'Asia/Taipei';
    public const TZ_TJ = 'Asia/Dushanbe';
    public const TZ_TZ = 'Africa/Dar_es_Salaam';
    public const TZ_TH = 'Asia/Bangkok';
    public const TZ_TL = 'Asia/Dili';
    public const TZ_TG = 'Africa/Lome';
    public const TZ_TK = 'Pacific/Fakaofo';
    public const TZ_TO = 'Pacific/Tongatapu';
    public const TZ_TT = 'America/Port_of_Spain';
    public const TZ_TN = 'Africa/Tunis';
    public const TZ_TR = 'Europe/Istanbul';
    public const TZ_TM = 'Asia/Ashgabat';
    public const TZ_TC = 'America/Grand_Turk';
    public const TZ_TV = 'Pacific/Funafuti';
    public const TZ_UG = 'Africa/Kampala';
    public const TZ_UA_KI = 'Europe/Kiev';
    public const TZ_UA_SI = 'Europe/Simferopol';
    public const TZ_UA_UZ = 'Europe/Uzhgorod';
    public const TZ_UA_ZA = 'Europe/Zaporozhye';
    public const TZ_AE = 'Asia/Dubai';
    public const TZ_GB = 'Europe/London';
    public const TZ_US_AD = 'America/Adak';
    public const TZ_US_AN = 'America/Anchorage';
    public const TZ_US_BO = 'America/Boise';
    public const TZ_US_CH = 'America/Chicago';
    public const TZ_US_DEN = 'America/Denver';
    public const TZ_US_DET = 'America/Detroit';
    public const TZ_US_IN = 'America/Indiana/Indianapolis';
    public const TZ_US_KN = 'America/Indiana/Knox';
    public const TZ_US_MA = 'America/Indiana/Marengo';
    public const TZ_US_PE = 'America/Indiana/Petersburg';
    public const TZ_US_TE = 'America/Indiana/Tell_City';
    public const TZ_US_VE = 'America/Indiana/Vevay';
    public const TZ_US_VI = 'America/Indiana/Vincennes';
    public const TZ_US_WI = 'America/Indiana/Winamac';
    public const TZ_US_JU = 'America/Juneau';
    public const TZ_US_LO = 'America/Kentucky/Louisville';
    public const TZ_US_MO = 'America/Kentucky/Monticello';
    public const TZ_US_LA = 'America/Los_Angeles';
    public const TZ_US_ME = 'America/Menominee';
    public const TZ_US_METL = 'America/Metlakatla';
    public const TZ_US_NE = 'America/New_York';
    public const TZ_US_NO = 'America/Nome';
    public const TZ_US_BE = 'America/North_Dakota/Beulah';
    public const TZ_US_CE = 'America/North_Dakota/Center';
    public const TZ_US_NS = 'America/North_Dakota/New_Salem';
    public const TZ_US_PH = 'America/Phoenix';
    public const TZ_US_SI = 'America/Sitka';
    public const TZ_US_YA = 'America/Yakutat';
    public const TZ_US_HO = 'Pacific/Honolulu';
    public const TZ_UM_MI = 'Pacific/Midway';
    public const TZ_UM_WA = 'Pacific/Wake';
    public const TZ_UY = 'America/Montevideo';
    public const TZ_UZ_SA = 'Asia/Samarkand';
    public const TZ_UZ_TA = 'Asia/Tashkent';
    public const TZ_VU = 'Pacific/Efate';
    public const TZ_VE = 'America/Caracas';
    public const TZ_VN = 'Asia/Ho_Chi_Minh';
    public const TZ_VG = 'America/Tortola';
    public const TZ_VI = 'America/St_Thomas';
    public const TZ_WF = 'Pacific/Wallis';
    public const TZ_EH = 'Africa/El_Aaiun';
    public const TZ_YE = 'Asia/Aden';
    public const TZ_ZM = 'Africa/Lusaka';
    public const TZ_ZW = 'Africa/Harare';


    public $countries = [
                        'AF' => 'Afghanistan',
                        'AX' => 'Aland Islands',
                        'AL' => 'Albania',
                        'DZ' => 'Algeria',
                        'AS' => 'American Samoa',
                        'AD' => 'Andorra',
                        'AO' => 'Angola',
                        'AI' => 'Anguilla',
                        'AQ' => 'Antarctica',
                        'AG' => 'Antigua And Barbuda',
                        'AR' => 'Argentina',
                        'AM' => 'Armenia',
                        'AW' => 'Aruba',
                        'AU' => 'Australia',
                        'AT' => 'Austria',
                        'AZ' => 'Azerbaijan',
                        'BS' => 'Bahamas',
                        'BH' => 'Bahrain',
                        'BD' => 'Bangladesh',
                        'BB' => 'Barbados',
                        'BY' => 'Belarus',
                        'BE' => 'Belgium',
                        'BZ' => 'Belize',
                        'BJ' => 'Benin',
                        'BM' => 'Bermuda',
                        'BT' => 'Bhutan',
                        'BO' => 'Bolivia',
                        'BA' => 'Bosnia And Herzegovina',
                        'BW' => 'Botswana',
                        'BV' => 'Bouvet Island',
                        'BR' => 'Brazil',
                        'IO' => 'British Indian Ocean Territory',
                        'BN' => 'Brunei Darussalam',
                        'BG' => 'Bulgaria',
                        'BF' => 'Burkina Faso',
                        'BI' => 'Burundi',
                        'KH' => 'Cambodia',
                        'CM' => 'Cameroon',
                        'CA' => 'Canada',
                        'CV' => 'Cape Verde',
                        'KY' => 'Cayman Islands',
                        'CF' => 'Central African Republic',
                        'TD' => 'Chad',
                        'CL' => 'Chile',
                        'CN' => 'China',
                        'CX' => 'Christmas Island',
                        'CC' => 'Cocos (Keeling) Islands',
                        'CO' => 'Colombia',
                        'KM' => 'Comoros',
                        'CG' => 'Congo',
                        'CD' => 'Congo, Democratic Republic',
                        'CK' => 'Cook Islands',
                        'CR' => 'Costa Rica',
                        'CI' => 'Cote D\'Ivoire',
                        'HR' => 'Croatia',
                        'CU' => 'Cuba',
                        'CY' => 'Cyprus',
                        'CZ' => 'Czech Republic',
                        'DK' => 'Denmark',
                        'DJ' => 'Djibouti',
                        'DM' => 'Dominica',
                        'DO' => 'Dominican Republic',
                        'EC' => 'Ecuador',
                        'EG' => 'Egypt',
                        'SV' => 'El Salvador',
                        'GQ' => 'Equatorial Guinea',
                        'ER' => 'Eritrea',
                        'EE' => 'Estonia',
                        'ET' => 'Ethiopia',
                        'FK' => 'Falkland Islands (Malvinas)',
                        'FO' => 'Faroe Islands',
                        'FJ' => 'Fiji',
                        'FI' => 'Finland',
                        'FR' => 'France',
                        'GF' => 'French Guiana',
                        'PF' => 'French Polynesia',
                        'TF' => 'French Southern Territories',
                        'GA' => 'Gabon',
                        'GM' => 'Gambia',
                        'GE' => 'Georgia',
                        'DE' => 'Germany',
                        'GH' => 'Ghana',
                        'GI' => 'Gibraltar',
                        'GR' => 'Greece',
                        'GL' => 'Greenland',
                        'GD' => 'Grenada',
                        'GP' => 'Guadeloupe',
                        'GU' => 'Guam',
                        'GT' => 'Guatemala',
                        'GG' => 'Guernsey',
                        'GN' => 'Guinea',
                        'GW' => 'Guinea-Bissau',
                        'GY' => 'Guyana',
                        'HT' => 'Haiti',
                        'HM' => 'Heard Island & Mcdonald Islands',
                        'VA' => 'Holy See (Vatican City State)',
                        'HN' => 'Honduras',
                        'HK' => 'Hong Kong',
                        'HU' => 'Hungary',
                        'IS' => 'Iceland',
                        'IN' => 'India',
                        'ID' => 'Indonesia',
                        'IR' => 'Iran, Islamic Republic Of',
                        'IQ' => 'Iraq',
                        'IE' => 'Ireland',
                        'IM' => 'Isle Of Man',
                        'IL' => 'Israel',
                        'IT' => 'Italy',
                        'JM' => 'Jamaica',
                        'JP' => 'Japan',
                        'JE' => 'Jersey',
                        'JO' => 'Jordan',
                        'KZ' => 'Kazakhstan',
                        'KE' => 'Kenya',
                        'KI' => 'Kiribati',
                        'KR' => 'Korea',
                        'KW' => 'Kuwait',
                        'KG' => 'Kyrgyzstan',
                        'LA' => 'Lao People\'s Democratic Republic',
                        'LV' => 'Latvia',
                        'LB' => 'Lebanon',
                        'LS' => 'Lesotho',
                        'LR' => 'Liberia',
                        'LY' => 'Libyan Arab Jamahiriya',
                        'LI' => 'Liechtenstein',
                        'LT' => 'Lithuania',
                        'LU' => 'Luxembourg',
                        'MO' => 'Macao',
                        'MK' => 'Macedonia',
                        'MG' => 'Madagascar',
                        'MW' => 'Malawi',
                        'MY' => 'Malaysia',
                        'MV' => 'Maldives',
                        'ML' => 'Mali',
                        'MT' => 'Malta',
                        'MH' => 'Marshall Islands',
                        'MQ' => 'Martinique',
                        'MR' => 'Mauritania',
                        'MU' => 'Mauritius',
                        'YT' => 'Mayotte',
                        'MX' => 'Mexico',
                        'FM' => 'Micronesia, Federated States Of',
                        'MD' => 'Moldova',
                        'MC' => 'Monaco',
                        'MN' => 'Mongolia',
                        'ME' => 'Montenegro',
                        'MS' => 'Montserrat',
                        'MA' => 'Morocco',
                        'MZ' => 'Mozambique',
                        'MM' => 'Myanmar',
                        'NA' => 'Namibia',
                        'NR' => 'Nauru',
                        'NP' => 'Nepal',
                        'NL' => 'Netherlands',
                        'AN' => 'Netherlands Antilles',
                        'NC' => 'New Caledonia',
                        'NZ' => 'New Zealand',
                        'NI' => 'Nicaragua',
                        'NE' => 'Niger',
                        'NG' => 'Nigeria',
                        'NU' => 'Niue',
                        'NF' => 'Norfolk Island',
                        'MP' => 'Northern Mariana Islands',
                        'NO' => 'Norway',
                        'OM' => 'Oman',
                        'PK' => 'Pakistan',
                        'PW' => 'Palau',
                        'PS' => 'Palestinian Territory, Occupied',
                        'PA' => 'Panama',
                        'PG' => 'Papua New Guinea',
                        'PY' => 'Paraguay',
                        'PE' => 'Peru',
                        'PH' => 'Philippines',
                        'PN' => 'Pitcairn',
                        'PL' => 'Poland',
                        'PT' => 'Portugal',
                        'PR' => 'Puerto Rico',
                        'QA' => 'Qatar',
                        'RE' => 'Reunion',
                        'RO' => 'Romania',
                        'RU' => 'Russian Federation',
                        'RW' => 'Rwanda',
                        'BL' => 'Saint Barthelemy',
                        'SH' => 'Saint Helena',
                        'KN' => 'Saint Kitts And Nevis',
                        'LC' => 'Saint Lucia',
                        'MF' => 'Saint Martin',
                        'PM' => 'Saint Pierre And Miquelon',
                        'VC' => 'Saint Vincent And Grenadines',
                        'WS' => 'Samoa',
                        'SM' => 'San Marino',
                        'ST' => 'Sao Tome And Principe',
                        'SA' => 'Saudi Arabia',
                        'SN' => 'Senegal',
                        'RS' => 'Serbia',
                        'SC' => 'Seychelles',
                        'SL' => 'Sierra Leone',
                        'SG' => 'Singapore',
                        'SK' => 'Slovakia',
                        'SI' => 'Slovenia',
                        'SB' => 'Solomon Islands',
                        'SO' => 'Somalia',
                        'ZA' => 'South Africa',
                        'GS' => 'South Georgia And Sandwich Isl.',
                        'ES' => 'Spain',
                        'LK' => 'Sri Lanka',
                        'SD' => 'Sudan',
                        'SR' => 'Suriname',
                        'SJ' => 'Svalbard And Jan Mayen',
                        'SZ' => 'Swaziland',
                        'SE' => 'Sweden',
                        'CH' => 'Switzerland',
                        'SY' => 'Syrian Arab Republic',
                        'TW' => 'Taiwan',
                        'TJ' => 'Tajikistan',
                        'TZ' => 'Tanzania',
                        'TH' => 'Thailand',
                        'TL' => 'Timor-Leste',
                        'TG' => 'Togo',
                        'TK' => 'Tokelau',
                        'TO' => 'Tonga',
                        'TT' => 'Trinidad And Tobago',
                        'TN' => 'Tunisia',
                        'TR' => 'Turkey',
                        'TM' => 'Turkmenistan',
                        'TC' => 'Turks And Caicos Islands',
                        'TV' => 'Tuvalu',
                        'UG' => 'Uganda',
                        'UA' => 'Ukraine',
                        'AE' => 'United Arab Emirates',
                        'GB' => 'United Kingdom',
                        'US' => 'United States',
                        'UM' => 'United States Outlying Islands',
                        'UY' => 'Uruguay',
                        'UZ' => 'Uzbekistan',
                        'VU' => 'Vanuatu',
                        'VE' => 'Venezuela',
                        'VN' => 'Viet Nam',
                        'VG' => 'Virgin Islands, British',
                        'VI' => 'Virgin Islands, U.S.',
                        'WF' => 'Wallis And Futuna',
                        'EH' => 'Western Sahara',
                        'YE' => 'Yemen',
                        'ZM' => 'Zambia',
                        'ZW' => 'Zimbabwe',
                    ];

    /**
     * Returns a numerically indexed array containing all defined timezone identifiers per country.
     *
     * @param string $countryCode A two-letter ISO 3166-1 compatible country code.
     * @return array timeZone identifiers
     */
    public static function getIdentifiersPerCountry($countryCode)
    {
        return \DateTimeZone::listIdentifiers(\DateTimeZone::PER_COUNTRY, $countryCode);
    }
}
